#!/usr/bin/env bash

echo
echo "`date -u` ~ ~ ~ nightly benchmark suite start ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~"
echo

# thank you to http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
BASE_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."

cd "$BASE_DIR/runner"
echo `pwd`

source "$HOME/.bash_profile"
source "$HOME/.rvm/scripts/rvm"
rvm "1.8.7-p370@benchmark"
echo "Starting benchmark with `rvm current`"

ruby scripts/kill_extraneous_apps.rb

echo "Grabbing brianhempel/isrubyfastyet master from Github"
git pull --rebase

echo "Updating Homebrew"
brew update

# run the suite!!
rake benchmark_suite                                           &&
	git add ../runner/benchmarks/**/Gemfile_*.lock             &&
	(git commit -m 'Autorunner: Gemfile.lock updates' || true) &&
	git add ../results/*                                       &&
	git commit -m 'Autorunner: Results'                        &&
	git pull --rebase                                          &&
	git push origin master                                     &&
	cd "$BASE_DIR/isrubyfastyet.com"                           &&
	echo `pwd`                                                 &&
	./transfer_site_to_s3

echo
echo "`date -u` ~ ~ ~ nightly benchmark suite finish ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~"
echo

# restart the computer without sudo
# applescript FTW
# http://www.dssw.co.uk/blog/2010/09/09/how-to-shut-down-your-mac-using-applescript/
osascript -e 'tell application "Finder"
  shut down
end tell'
