#!/usr/bin/env bash

# setup_ruby <rvm_ruby_name> <install arguments> <before_install_commands>

source "$HOME/.rvm/scripts/rvm"

rvm get stable --without-gems=rubygems-bundler

if rvm "$1" && (rvm current | grep '-head')
then
  # the ruby is installed and it's head
  echo "$3"
  eval "$3"
  echo "rvm reinstall \"$1 $2\""
  rvm reinstall "$1 $2"
fi

rvm "$1@benchmark" --create || (echo "$3"; eval "$3"; echo "rvm install \"$1 $2\""; rvm install "$1 $2" && rvm "$1@benchmark" --create)
