#!/usr/bin/env bash

# remove_rvm_repos (no arguments)

echo "Removing RVM repos"
if [ "$IRFY_DEV_MODE" != 'true' ]
then
  echo "rm -rf $HOME/.rvm/repos/*"
  rm -rf $HOME/.rvm/repos/*
else
  echo "Skipping repo removal because IRFY_DEV_MODE=true"
fi
