#!/usr/bin/env bash

# ruby_version_in_rvm <rvm_ruby_name> <ruby_command>

source "$HOME/.rvm/scripts/rvm"

if rvm "$1"
then
	if ! eval "$2 -v"
	then
  	echo "command failed: $2 -v"
  	exit 1
  fi
else
	echo "rvm failed to switch to $1"
	exit 1
fi