#!/usr/bin/env bash

# setup_bundle <directory_with_gemfile> <rvm_ruby_name> <before_bundle_commands>

source "$HOME/.rvm/scripts/rvm"

cd "$1"
pwd

rvm "$2@benchmark"

# which bundle isn't robust enough under RVM
(bundle help >& /dev/null) || gem install bundler

if [ -e "Gemfile.lock" ]
then
    rm Gemfile.lock
fi

if [ -e "Gemfile_$2.lock" ]
then
    cp "Gemfile_$2.lock" "Gemfile.lock"
fi

echo "$3"
eval "$3"
bundle install

if [ -e "Gemfile_$2.lock" ]
then
    rm "Gemfile_$2.lock"
fi

cp Gemfile.lock "Gemfile_$2.lock"
