#!/usr/bin/env bash

# setup_bundle <directory_with_gemfile> <rvm_ruby_name> <before_bundle_commands>

source "$HOME/.rvm/scripts/rvm"

cd "$1"
pwd

rvm "$2@benchmark"

# which bundle isn't robust enough under RVM
(bundle help >& /dev/null) || gem install bundler

if [ -e "Gemfile.lock" ]
then
    rm Gemfile.lock
fi

if [ -e "Gemfile_$2.lock" ]
then
    cp "Gemfile_$2.lock" "Gemfile.lock"
fi

echo "$3"
eval "$3"

if ! bundle install
then
  rm "Gemfile.lock"
  bundle install
fi

if [ -e "Gemfile.lock" ]
then
  if [ -e "Gemfile_$2.lock" ]
  then
      rm "Gemfile_$2.lock"
  fi

  cp Gemfile.lock "Gemfile_$2.lock"
else
  # bundle failed? maybe re-installing ruby will help
  # re-install next night

  if (curl https://status.github.com/api/status.json | grep "good") # internet/Github is working
  then
    # thank you to http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
    SCRIPTS_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

    eval "$SCRIPTS_DIR/uninstall_ruby $2"
  fi
fi
