#!/usr/bin/env bash

# setup_ruby <rvm_ruby_name> <install arguments> <before_install_commands>

# thank you to http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
SCRIPTS_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


function install_or_reinstall {
  if (echo $1 | grep '-head')
  then
    eval "$SCRIPTS_DIR/remove_rvm_repos"
  fi

  echo "$3"
  eval "$3"

  if rvm "$1"
  then
    echo "rvm reinstall --autolibs=enabled --reconfigure $2 $1"
    rvm reinstall --autolibs=enabled --reconfigure $2 $1
    return $?
  else
    echo "rvm install --autolibs=enabled --reconfigure $2 $1"
    rvm install --autolibs=enabled --reconfigure $2 $1
    return $?
  fi
}

function try_install_or_reinstall {
  if (curl https://status.github.com/api/status.json | grep "good") # internet/Github is working
  then
    if ! install_or_reinstall "$1" "$2" "$3"
    then
      echo "Removing $1 and reinstalling.."
      eval "$SCRIPTS_DIR/uninstall_ruby $1"

      install_or_reinstall "$1" "$2" "$3"
      return $?
    else
      return 0
    fi
  else
    echo "Cannot install, internet or Github is down."
    return 1
  fi
}

source "$HOME/.rvm/scripts/rvm"

if [ "$IRFY_DEV_MODE" != 'true' ]
then
  rvm get stable --without-gems=rubygems-bundler
fi

if (echo $1 | grep '-head')
then
  try_install_or_reinstall "$1" "$2" "$3"
fi

rvm "$1@benchmark" --create || (try_install_or_reinstall "$1" "$2" "$3" && rvm "$1@benchmark" --create)
